# Generated by Django 5.2.9 on 2025-12-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('song_id', models.CharField(db_column='id', max_length=64)),
                ('title', models.CharField(max_length=255)),
                ('danceability', models.FloatField()),
                ('energy', models.FloatField()),
                ('key', models.IntegerField()),
                ('loudness', models.FloatField()),
                ('mode', models.IntegerField()),
                ('acousticness', models.FloatField()),
                ('instrumentalness', models.FloatField()),
                ('liveness', models.FloatField()),
                ('valence', models.FloatField()),
                ('tempo', models.FloatField()),
                ('duration_ms', models.IntegerField()),
                ('time_signature', models.IntegerField()),
                ('num_bars', models.IntegerField()),
                ('num_sections', models.IntegerField()),
                ('num_segments', models.IntegerField()),
                ('song_class', models.IntegerField(db_column='class')),
                ('song_rating', models.IntegerField()),
            ],
            options={
                'db_table': 'songs_normalized',
                'managed': False,
            },
        ),
    ]
